### ISSUE TITLE
[Questions and relate]hosting on other services

### ISSUE THREAD

**Issue by jackthenewbie** [MadeBaruna/paimon-moe-api#4]
![image](https://user-images.githubusercontent.com/55600733/172355361-1ec9700a-d428-49d4-b3fb-e9bf7b07f957.png)
Trying to put one on Railway.app (similar to heroku), but got some error. Is hosting it on other serivces possible?
full log: [https://paste.linux.chat/?95c28092f77b6c3e#C2JDYxEHu95XcxdSVUPghiJZQDJLEreLuc8hMkbE2eWY](url)
cuz when I run it from instruction paimon-moe, postgres and moe_api_api keep restarting, I know about the postgres restarting probably cuz I haven't install it yet. So does moe-api_api depend on it? 
![image](https://user-images.githubusercontent.com/55600733/172357804-40226aa3-f733-4ce9-bee1-5e95eb57c5c5.png)

**Comment by MadeBaruna** [comment]
you need proxies.txt, it contains list of ip:port

**Comment by jackthenewbie** [comment]
@MadeBaruna what protocol? http? Or any?

**Comment by MadeBaruna** [comment]
http https://github.com/MadeBaruna/paimon-moe-api/blob/dcf8bd68a2cda92b3c1f6694c92df882fa693212/src/routes/corsProxy.ts#L13

**Comment by jackthenewbie** [comment]
```
Error: invalid banner
{"message":"failed processing wish tally summary","name":"wish-tally-calculate","id":400006}
at Queue.calculateWishTally (/api/queue/tally.js:29:15)
at processTicksAndRejections (internal/process/task_queues.js:95:5)
{"message":"processing wish tally summary","name":"wish-tally-calculate","id":400008,"time":"2022-06-12T10:06:45+00:00"}
{"message":"failed processing wish tally summary","name":"wish-tally-calculate","id":400008}
Error: invalid banner
at Queue.calculateWishTally (/api/queue/tally.js:29:15)
at processTicksAndRejections (internal/process/task_queues.js:95:5)
{"message":"processing wish tally summary","name":"wish-tally-calculate","id":400011,"time":"2022-06-12T10:06:45+00:00"}
Error: invalid banner
{"message":"failed processing wish tally summary","name":"wish-tally-calculate","id":400011}
at Queue.calculateWishTally (/api/queue/tally.js:29:15)
at processTicksAndRejections (internal/process/task_queues.js:95:5)
{"message":"processing wish tally summary","name":"wish-tally-calculate","id":400013,"time":"2022-06-12T10:06:45+00:00"}
Error: invalid banner
at Queue.calculateWishTally (/api/queue/tally.js:29:15)
{"message":"failed processing wish tally summary","name":"wish-tally-calculate","id":400013}
at processTicksAndRejections (internal/process/task_queues.js:95:5)
{"message":"processing wish tally summary","name":"wish-tally-calculate","id":400016,"time":"2022-06-12T10:06:45+00:00"}
Error: invalid banner
{"message":"failed processing wish tally summary","name":"wish-tally-calculate","id":400016}
at Queue.calculateWishTally (/api/queue/tally.js:29:15)
at processTicksAndRejections (internal/process/task_queues.js:95:5)
{"message":"processing wish tally summary","name":"wish-tally-calculate","id":400020,"time":"2022-06-12T10:06:45+00:00"}
Error: invalid banner
at Queue.calculateWishTally (/api/queue/tally.js:29:15)
at processTicksAndRejections (internal/process/task_queues.js:95:5)
{"message":"failed processing wish tally summary","name":"wish-tally-calculate","id":400020}
{"message":"processing wish tally summary","name":"wish-tally-calculate","id":400022,"time":"2022-06-12T10:06:45+00:00"}
{"message":"failed processing wish tally summary","name":"wish-tally-calculate","id":400022}
Error: invalid banner
at Queue.calculateWishTally (/api/queue/tally.js:29:15)
at processTicksAndRejections (internal/process/task_queues.js:95:5)
{"message":"processing wish tally summary","name":"wish-tally-calculate","id":400025,"time":"2022-06-12T10:06:45+00:00"}
{"message":"failed processing wish tally summary","name":"wish-tally-calculate","id":400025}
Error: invalid banner
at Queue.calculateWishTally (/api/queue/tally.js:29:15)
at processTicksAndRejections (internal/process/task_queues.js:95:5)
{"message":"processing wish tally summary","name":"wish-tally-calculate","id":400027,"time":"2022-06-12T10:06:45+00:00"}
{"message":"failed processing wish tally summary","name":"wish-tally-calculate","id":400027}
Error: invalid banner
at Queue.calculateWishTally (/api/queue/tally.js:29:15)
at processTicksAndRejections (internal/process/task_queues.js:95:5)
{"message":"processing wish tally summary","name":"wish-tally-calculate","id":400029,"time":"2022-06-12T10:06:45+00:00"}
{"message":"failed processing wish tally summary","name":"wish-tally-calculate","id":400029}
Error: invalid banner
at Queue.calculateWishTally (/api/queue/tally.js:29:15)
at processTicksAndRejections (internal/process/task_queues.js:95:5)
Server failed to start!
QueryFailedError: index "wish_uniqueId_idx" does not exist
at new QueryFailedError (/api/node_modules/.pnpm/typeorm@0.2.31/node_modules/typeorm/error/QueryFailedError.js:11:28)
at PostgresQueryRunner.<anonymous> (/api/node_modules/.pnpm/typeorm@0.2.31/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:247:31)
at step (/api/node_modules/.pnpm/tslib@1.14.1/node_modules/tslib/tslib.js:141:27)
at Object.throw (/api/node_modules/.pnpm/tslib@1.14.1/node_modules/tslib/tslib.js:122:57)
at rejected (/api/node_modules/.pnpm/tslib@1.14.1/node_modules/tslib/tslib.js:113:69)
at processTicksAndRejections (internal/process/task_queues.js:95:5) {
length: 112,
severity: 'ERROR',
code: '42704',
detail: undefined,
hint: undefined,
position: undefined,
internalPosition: undefined,
internalQuery: undefined,
where: undefined,
schema: undefined,
table: undefined,
column: undefined,
dataType: undefined,
constraint: undefined,
file: 'tablecmds.c',
line: '1211',
routine: 'DropErrorMsgNonExistent',
query: 'DROP INDEX "wish_uniqueId_idx"',
parameters: []
}
```
so I think somehow I make it run, but now encounter another error. Is it problem on my side or the code? not being rude, just curious:)
edit: oh wait probably because of my proxy server, will try it out and ask again later, thanks

**Comment by jackthenewbie** [comment]
@MadeBaruna uhh could you have any idea what is wrong with the [output](https://github.com/MadeBaruna/paimon-moe-api/issues/4#issuecomment-1153121322)? because im having the same problem after redeploy container on my pi
